Correct shyaml installation on fedora28
Fixed failure to install a working version of shyaml on fedora28 where
shyaml was installed but not functioning because python3-yaml was
not installed.

Also fix problem that caused installation of python2 packages on
python3 systems due to the wildcards, we removed the wildcards.

Also removed single quoates from exclude param because bash did
escape them, which probably caused the excludes to be ignored.

See http://logs.openstack.org/16/614516/2/check/tripleo-ci-fedora-28-standalone/7b10b3a/job-output.txt.gz#_2018-11-01_15_05_51_598966

File "/usr/bin/shyaml", line 11, in <module>
import yaml
ModuleNotFoundError: No module named 'yaml'

Depends-On: https://review.openstack.org/#/c/614762

Change-Id: I0ffe2af9bc56d4185e2ad16dd1800bf028070414