Revert Update Twitter Bootstrap to version 3
This commit is causing CI to fail with
CommandError: An error occured during rendering
/opt/stack/.../openstack_dashboard/templates/_stylesheets.html:
Error parsing block:

Change-Id: Ie3f3f623ed0eae93b0a622e12760eecc6559e1a1